### PR TITLE
Fixes #1 where we would not compile and process certain regex strings

### LINKED ISSUE #1: sigma rule modifiers not working
Modifiers such as |endswith |startswith do not seem to be working.

rule:
```
title: test
id: test
detection:
    selection:
        foo|endswith: "bar"
    condition: selection
```
    
`echo '{"foo": "foobar"}' | ./go-sigma-rule-engine run --rules-dir rules/`

Expected result would be a match, but no match is found. Same rule without the modifier and search value of `foobar` will find a match. Glob pattern in search value also works - so search value `*bar` without the modifier `|endswith` works.

### PR DESCRIPTION
**Pull request by newodahs**
Basically, due to how globs are processed, if a regex using the new `re` modifier had the 0-or-more character (`*`) in it, we would not compile or process the string as a regex, but rather a glob.

This is a quick and dirty fix to prevent that from happening.

### CODE REVIEW

File: pkg/sigma/v2/tree.go [hunk 1]
```diff
@@ -204,6 +204,7 @@ func extractAndBuildBranches(d Detection, g string) ([]Branch, error) {
 func extractWildcardIdents(d Detection, g string) ([]interface{}, error) {
 	rules := make([]interface{}, 0)
 	for k, v := range d {
+		//I don't think this needs to use the other glob library?
```
Comment (markuskont) [inline pkg/sigma/v2/tree.go:207]: Maybe not, but I would prefer to stick to just one library for keeping external imports to a minimum. 

Plus, I think even if new code is more complex, at least it's consistent across the codebase.

File: pkg/sigma/v2/pattern.go [hunk 2]
```diff
@@ -71,32 +73,56 @@ func NewStringMatcher(
...
 				matcher = append(matcher, RegexPattern{Re: re})
-			case TextPatternSuffix:
-				matcher = append(matcher, SuffixPattern{Token: p, Lowercase: lower})
-			case TextPatternPrefix:
-				matcher = append(matcher, PrefixPattern{Token: p, Lowercase: lower})
-			default:
+			} else if mod == TextPatternKeyword {
+				//this is a bit hacky, basically if the pattern coming in is a keyword and did not appear
+				//to be a regex, always process it as a 'contains' style glob (can appear anywhere...)
+				//this is due, I believe, on how keywords are generally handled, where it is likely a random
```
Comment (markuskont) [inline pkg/sigma/v2/pattern.go:111]: Yes, exactly. That's the way I see keyword matches as well. For stuff like syslog `MSG` part or event log `Message`, which are basically big text blobs that can contain anything. Sigma keyword I saw as rulewrited saying `I dont care, just match in whatever field is relevant for this sort of stuff` when dealing with structured messages.

So I support the idea of doing general matches over them. Selection type is when we need to be specific.

File: pkg/sigma/v2/tree.go (hunk 1 above)
Comment (newodahs) [reply pkg/sigma/v2/tree.go]: Changed with with 4e34d32336a852448f9ef77829afde342bc1416b, v2 now uses globwas everywhere.
